### ISSUE TITLE
Porównywanie doc/x

### ISSUE THREAD

**Issue by marcinsendyka** [suowik/plagiator#1]
Czy w takim razie rezygnujemy z swinga? Znasz jakies metody osadzenia tego w swingu ? Ew. czy udostepniaja oni jakis plugin, zeby nie przkierowywac do ich strony [aplikacja chyba powinna chodzic offline)

**Comment by Damianiero** [comment]
Myślałem, żeby zrobić tak, że otwiera się sama przeglądarka z tą daną stroną, przy czym - musi być dostęp do internetu. Nie wiedziałem, że jest takie wymaganie, by chodziło w trybie offline:/

**Comment by MarcinPlawecki** [comment]
mysle, ze nie ma problemu, aby otworzyc porownanie za pomoca przegladarki na tej stronie. w wymaganiach nie bylo mowy, ze musi to dzialac offline. pytanie tylko, czy ta strona jest odpowiednia. pokazuje roznice, a my potrzebujemy podobienstwa

**Comment by marcinsendyka** [comment]
no ten tryb offline to faktycznie troche wzielem z dupy:D spytamy dzis o to. Trzeba bedzie dzis tez wyznaczyc kogos zeby sprawdzil dokladniej czy jest sens sie to bawic czy szukamy czego innego

**Comment by Damianiero** [comment]
Pewnie trafiliście na tę stronę:
http://www.docx4java.org/trac/docx4j
*
Na zajęciach coś poczytam o tym. Będę szczery, że pokazywanie podobieństw jest dla mnie w tym projekcie największym wyzwaniem. Szkoda, że nie mam dużo czasu na to, prośba do wszystkich, żeby poszukali parę innych rozwiązań. **

Ponadto proponuję trochę oszukać w tym projekcie. Może przesadziłem z tym oszukaniem...:P Wyjaśniam:
1) Za pomocą skomplikowanych algorytmów wskazać, czy faktycznie jest plagiat. 
2) Jeśli jest stwierdzone, że mamy plagiat, to na zawołanie dane dwa dokumenty dać właśnie do czegoś w stylu docx4java\* (diff) za pomocą paru linijek kodu i tyle. Będą pokazane podobieństwa, wszyscy będą zadowoleni:P 
- Pewnie ktoś zauważył, że powyższa biblioteka działa tylko na docx. Wiem o tym, dlatego wszystko byłoby konwertowane do tego formatu - bibliotek do tego będzie sporo.

*\* Prosiłbym o nie utożsamianie mnie z tym issue:P Jak pisałem wyżej, trochę wynikło mi spraw życiowych, także pewnie będę się jednak bronił we wrześniu, jak nie w październiku... więc nie chcę opóźniać projektu:) Ale w każdym razie będę się starać;b

**Comment by b4rt3k** [comment]
Ja bym to robił najprościej jak się da. Dać dwa text fieldy obok sieie w gui. Fcja sprawdzająca plagiat zwracała by też fragmenty tekstu, które są takie same. Mając dany fragment da się chyba jakos zakolorowac w swingu daną cześć tekstu.
Dnia 13 marca 2013 9:42 Damianiero &lt;notifications@github.com&gt; napisał(a):
Pewnie trafiliście na tę stronę:
http://www.docx4java.org/trac/docx4j
*
Na zajęciach coś poczytam o tym. Będę szczery, że pokazywanie podobieństw jest dla mnie w tym projekcie największym wyzwaniem. Szkoda, że nie mam dużo czasu na to, prośba do wszystkich, żeby poszukali parę innych rozwiązań. **
Ponadto proponuję trochę oszukać w tym projekcie. Może przesadziłem z tym oszukaniem...:P Wyjaśniam:
1) Za pomocą skomplikowanych algorytmów wskazać, czy faktycznie jest plagiat.
2) Jeśli jest stwierdzone, że mamy plagiat, to na zawołanie dane dwa dokumenty dać właśnie do czegoś w stylu docx4java\* (diff) za pomocą paru linijek kodu i tyle. Będą pokazane podobieństwa, wszyscy będą zadowoleni:P
Pewnie ktoś zauważył, że powyższa biblioteka działa tylko na docx. Wiem o tym, dlatego wszystko byłoby konwertowane do tego formatu - bibliotek do tego myślę, że będzie sporo. *\* Prosiłbym o nie utożsamianie mnie z tym issue:P Jak pisałem wyżej, trochę wynikło mi spraw życiowych, także pewnie będę się jednak bronił we wrześniu, jak nie w październiku... więc nie chcę opóźniać projektu:)—

**Comment by Damianiero** [comment]
Tak Bartku, to byłoby najfajniejsze, bo byśmy potrzebowali tylko czysty tekst i na np. czerwono zaznaczali to samo. Problem chyba jest w tym, że mamy wymaganie, które mówi, że ma być zachowane formatowanie tekstu i pokazanie w faktycznym dokumencie, a nie już przemielonym.

**Comment by marcinsendyka** [comment]
Zgadza sie

**Comment by b4rt3k** [comment]
Oki. W takim razie ja jeszcze tez cos poszukam
Dnia 13 marca 2013 10:55 smajlo &lt;notifications@github.com&gt; napisał(a):
Zgadza sie

**Comment by MarcinPlawecki** [comment]
z tego co szukalem, widzę 2 opcje:
- może jednak rzeczywiście wyświetlać porównanie plain tekstow. warunkiem jest zachowanie chociazby akapitow i umieszczenie gdzies numerow stron.
- mozna tez podczas parsowania doc/docx do tekstu zachowac rowniez jakies informacje o formatowaniu. nastepnie po sprawdzeniu i zaznaczeniu podobienstw wyeksportowac to spowrotem do doc/docx, lub łatwiej - do pdf'a.

mysle, ze samo okienko z wynikami zawieraloby dwa teksty po dwoch stronach, i przyciski do nawigacji, w stylu "nastepne podobienstwo" i "poprzednie podobienstwo", aby nawigacja byla latwa i babka od razu widzi co to za podobienstwo i gdzie sie znajduje. a to, ze czcionka jest innego kroju czy rozmiaru nie ma wielkiego znaczenia.
