### ISSUE TITLE
Wybranie algorytmu sprawdzania tekstu.

### ISSUE THREAD

**Issue by suowik** [suowik/plagiator#5]
Paweł Ty najlepiej poznałeś algorytmy wyszukiwania podobieństw w tekście. Zrób ich podsumowanie i napisz, który według Ciebie będzie najłatwiejszy w implementacji (nie patrz na wydajność i skuteczność).

**Comment by psmektalski** [comment]
Wybierałbym pomiędzy dwoma algorytmami: KMP oraz Rabina-Karpa. Pierwszy jest łatwiejszy do zrozumienia, ale drugi oferuję większą dokładność. Z kolei czytałem, że do wyszukiwania plagiatu w kilku źródłach został użyty algorytm Rabina-Karpa. Jak chodzi o złożoność obliczeniową to jest podobna dla dwóch algorytmów. W algorytmie KMP bieżąco badamy pozycje w jakiej jesteśmy w przeszukiwanym tekście oraz we wzorcu. Oprócz tego możemy stworzyć tablicę tak zwanego cząstkowego dopasowania. Tablica ta wskazuje, gdzie musimy szukać początku nowego dopasowania w przypadku, gdy próba odnalezienia wystąpienia wzorca na obecnej pozycji zakończy się niepowodzeniem. Algorytm Rabin-Karpa przyspiesza porównywanie za pomocą funkcji skrótu. I jest lepszy od algorytmu KMP, jeżeli chcemy wyszukać w tekście wielokrotnie powtarzający się wzorzec.  

Sama implementacja algorytmu nie powinna być problemem. Pojawić się może problem z realizacją. To znaczy co zostanie wzięte jako wzorzec. Czy będzie wzorcem zdanie i na przykład po znalezieniu zdania w drugiej pracy doklejamy do wzorca kolejne zdanie i porównujemy dalej? 

Wybór myślę, że jest zależny w dużej mierze od piszących osób kod. Łatwiej by było zrealizować go przy pomocy KMP, bo jest łatwiejszy do zrozumienia. Z kolei lepszym rozwiązaniem jest użycie algorytmu Rabina-Karpa, który nie jest arcytrudny.

**Comment by b4rt3k** [comment]
Więc proponuje dzisiaj na zajęciach zdecydować który bierzemy i określićjak bierzemy ten wzorzec.
Dnia 20 marca 2013 1:45 Pasmek &lt;notifications@github.com&gt; napisał(a):
Wybierałbym pomiędzy dwoma algorytmami: KMP oraz Rabina-Karpa. Pierwszy jest łatwiejszy do zrozumienia, ale drugi oferuję większą dokładność. Z kolei czytałem, że do wyszukiwania plagiatu w kilku źródłach został użyty algorytm Rabina-Karpa. Jak chodzi o złożoność obliczeniową to jest podobna dla dwóch algorytmów. W algorytmie KMP bieżąco badamy pozycje w jakiej jesteśmy w przeszukiwanym tekście oraz we wzorcu. Oprócz tego możemy stworzyć tablicę tak zwanego cząstkowego dopasowania. Tablica ta wskazuje, gdzie musimy szukać początku nowego dopasowania w przypadku, gdy próba odnalezienia wystąpienia wzorca na obecnej pozycji zakończy się niepowodzeniem. Algorytm Rabin-Karpa przyspiesza porównywanie za pomocą funkcji skrótu. I jest lepszy od algorytmu KMP, jeżeli chcemy wyszukać w tekście wielokrotnie powtarzający się wzorzec.
Sama implementacja algorytmu nie powinna być problemem. Pojawić się może problem z realizacją. To znaczy co zostanie wzięte jako wzorzec. Czy będzie wzorcem zdanie i na przykład po znalezieniu zdania w drugiej pracy doklejamy do wzorca kolejne zdanie i porównujemy dalej?
Wybór myślę, że jest zależny w dużej mierze od piszących osób kod. Łatwiej by było zrealizować go przy pomocy KMP, bo jest łatwiejszy do zrozumienia. Z kolei lepszym rozwiązaniem jest użycie algorytmu Rabina-Karpa, który nie jest arcytrudny.

**Comment by b4rt3k** [comment]
Podsumował bym to co ustaliliśmy na ostatnich zajęciach:
- przy wyciąganiu tekstu z doc/docx zastępowac znaki w kolorze biały spacją
- wykrywac czcionkę (po co to miało być?)
- Aga wspominałą też coś o dziwnych znakach i mówiliśmy coś o mapie dziwnych znaków na ich  "normalne odpowiedniki" (te dziwne znaki miały by być zastępowane normalnymi na etapie wyciąganie tekstu z doc/docx?, a może po prostu wtedy wyjdzie że czcionka jest zła i wtedy nie analizujemy, dajemy warning?)
- jako że wybrałem ten algorytm z haszami, to ustaliliśmy chyba że zwracać ma on listę stringów zawierającą wspólne fragmenty 2 plików (coś jeszcze?)
- plik dzielimy na zdania (rozdzielone kropką, opcjonalną spacją i wielką literą), więc po preprocessingu zostają spacje i kropki aby dało się zidentyfikowac zdania
- wspominał ktoś coś o indeksach/kontekście (aby można było zakolorowac jakiś fragment)- mógłby ktoś napisac o co dokładnie chodziło?
   
  Jeśli coś źle napisałem lub coś pominąłem to mnie poprawcie, bo chciałbym to w weekend zakodzić, a chcę miec dobrze sprecyzowane zadanie :)
   
  Pozdro
  bartek
  Dnia 20 marca 2013 1:45 Pasmek &lt;notifications@github.com&gt; napisał(a):
  Wybierałbym pomiędzy dwoma algorytmami: KMP oraz Rabina-Karpa. Pierwszy jest łatwiejszy do zrozumienia, ale drugi oferuję większą dokładność. Z kolei czytałem, że do wyszukiwania plagiatu w kilku źródłach został użyty algorytm Rabina-Karpa. Jak chodzi o złożoność obliczeniową to jest podobna dla dwóch algorytmów. W algorytmie KMP bieżąco badamy pozycje w jakiej jesteśmy w przeszukiwanym tekście oraz we wzorcu. Oprócz tego możemy stworzyć tablicę tak zwanego cząstkowego dopasowania. Tablica ta wskazuje, gdzie musimy szukać początku nowego dopasowania w przypadku, gdy próba odnalezienia wystąpienia wzorca na obecnej pozycji zakończy się niepowodzeniem. Algorytm Rabin-Karpa przyspiesza porównywanie za pomocą funkcji skrótu. I jest lepszy od algorytmu KMP, jeżeli chcemy wyszukać w tekście wielokrotnie powtarzający się wzorzec.
  Sama implementacja algorytmu nie powinna być problemem. Pojawić się może problem z realizacją. To znaczy co zostanie wzięte jako wzorzec. Czy będzie wzorcem zdanie i na przykład po znalezieniu zdania w drugiej pracy doklejamy do wzorca kolejne zdanie i porównujemy dalej?
  Wybór myślę, że jest zależny w dużej mierze od piszących osób kod. Łatwiej by było zrealizować go przy pomocy KMP, bo jest łatwiejszy do zrozumienia. Z kolei lepszym rozwiązaniem jest użycie algorytmu Rabina-Karpa, który nie jest arcytrudny.

**Comment by psmektalski** [comment]
Wykrywanie czcionki miało być po to, żeby ktoś nie mógł pisać cyrylicą lub jeszcze innym językiem.
Jak chodzi o nietypowe znaki to miały być wychwytywane. I ta informacja miał być też dostarczana i później sprawdzana przez czynnik ludzki (tak mówiliśmy). Możliwe jednak, że lepszym pomysłem jest zmiana litery na prawidłową.

Skupiamy się w takim razie na zdaniach i je haszujemy. Jak chodzi o rezultat to oprócz pojawienia się fragmentów, musimy pamiętać na jakiej one są stronie. Wynikiem wtedy będzie fragment, który jest plagiatem oraz lokalizacja go w tekście. Jak chodzi o lokalizację zdania w tekście to padła propozycja dodawania informacji, ale poza haszem.

Problemem jak sobie przypominam poruszonym przez nas była sprawa, kiedy ktoś lekko modyfikuje zdanie. Nie wiem czy się zastanawiamy nad tą kwestią? Możliwe wtedy, że jak zdanie będzie lekko modyfikowane to będzie można to określić po hashu, który stworzyliśmy dla poszczególnych zdań. W tym momencie osobiście myślę, żeby opuścić tą kwestie, ale zostawić ją otwartą na później.

**Comment by MarcinPlawecki** [comment]
moim zdaniem mozna postapic tak:
- biale znaki zamieniac na spacje juz na etapie preprocessingu. mozna tez od razu zaznaczyc, ze nalezy zwrocic uwage na te miejsca (bo autor cos widocznie kombinowal w tym miejscu).
- wykrywac znaki z nie polskiego alfabetu i zaznaczyc, ze nalezy zwrocic na nie uwage. czyli moze to byc litera podobna do polskiej, aby oszukac plagiator.
- mysle, ze hashowanie calych zdan mija sie z celem. trzeba bedzie podzielic tekst na zdania, ktore moga byc przeciez bardzo dlugie i nawet jadac prosto z ksiazki, czy innego zrodla, jakies slowo raz za kiedy sie zamieni. do tego problematyczne jest wykrywanie, czy to zdanie, czy kropka dotyczy jakiegos skrotu itp.
  -mozna caly tekst podzielic na bloki, np 5 wyrazow. i na tych blokach pracowac. podzial bedzie prostszy, skutecznosc wieksza.

i zasada bylaby taka:
1) parsowanie doc/docx na plain text
2) podzial plain tekstu na bloki i ponumerowac kolejno te bloki
3) bloki poddac preprocessingowi, czyli usuwanie interpunkcji i krotkich wyrazow.
4) wykonac algorytm z hashami, porownujac bloki. blok jest plagiatem - mamy jego numer. algorytm zwraca liste blokow-plagiatow
5) zaznaczyc w plaintekscie wszystkie bloki z indeksami z listy - np. inne tło. 
5) wyswietlic plain text wraz z zaznaczonymi blokami, ktore zostaly wykryte jako plagiat - (nie bedzie to super ladny doc/docx, ale zwykly plain text, przed preprocessingiem, wiec latwo czytelny, a plagiaty beda zaznaczone np innym tlem. powinno krokowej wystarczyc).

**Comment by psmektalski** [comment]
Zastanawiam się jeszcze nad takim czymś. Jak podzielibyśmy ten tekst na bloki 5 wyrazowe to widzę taki problem. Co jeśli będziemy mieli taką sytuację:

Tekst początkowy w pierwszej pracy:
"Jednym z najprostszych praktycznych zastosowań algorytmu Rabina-Karpa jest wykrywanie plagiatu.."

Tekst początkowy w drugiej pracy:
"Wybór algorytmu. Jednym z najprostszych praktycznych zastosowań algorytmu Rabina-Karpa jest wykrywanie plagiatu.."

I teraz dzielimy tekst na bloki 5 wyrazowe. Wzorzec zostanie wzięty z pierwszej pracy: "Jednym najprostszych praktycznych zastosowań algorytmu". Porównują go z 5 wyrazowym blokiem z drugiej pracy nie otrzymamy, że zdanie: "Jednym z najprostszych praktycznych zastosowań algorytmu Rabina-Karpa jest wykrywanie plagiatu." jest takie same w obu pracach. 

Mam nadzieję, że przedstawiłem to dobrze. Teraz właśnie patrząc na to co napisałem wyżej, to co jakby 5 razy przeszukać pracę przesuwając o jeden wyraz wzorzec zhaszowany?

**Comment by b4rt3k** [comment]
Rozumiem, że każdy następny blok to przesunięcie o 1 wyraz. To rzeczywiście ma sens.  Dzięki za cenne uwagi. Jeśli ktoś ma jeszcze coś do dodania to niech pisze.  
Dnia 22 marca 2013 13:08 MarcinPlawecki &lt;notifications@github.com&gt; napisał(a):
moim zdaniem mozna postapic tak:
biale znaki zamieniac na spacje juz na etapie parsowania doc/docx. mozna tez od razu zaznaczyc, ze nalezy zwrocic uwage na te miejsca (bo autor cos widocznie kombinowal w tym miejscu).
wykrywac znaki z nie polskiego alfabetu i zaznaczyc, ze nalezy zwrocic na nie uwage. czyli moze to byc litera podobna do polskiej, aby oszukac plagiator.
mysle, ze hashowanie calych zdan mija sie z celem. trzeba bedzie podzielic tekst na zdania, ktore moga byc przeciez bardzo dlugie i nawet jadac prosto z ksiazki, czy innego zrodla, jakies slowo raz za kiedy sie zamieni. do tego problematyczne jest wykrywanie, czy to zdanie, czy kropka dotyczy jakiegos skrotu itp. -mozna caly tekst podzielic na bloki, np 5 wyrazow. i na tych blokach pracowac. podzial bedzie prostszy, skutecznosc wieksza.i zasada bylaby taka:
1) parsowanie doc/docx na plain text
2) podzial plain tekstu na bloki i ponumerowac kolejno te bloki
3) bloki poddac preprocessingowi, czyli usuwanie interpunkcji i krotkich wyrazow.
4) wykonac algorytm z hashami, porownujac bloki. blok jest plagiatem - mamy jego numer. algorytm zwraca liste blokow-plagiatow
5) zaznaczyc w plaintekscie wszystkie bloki z indeksami z listy - np. inne tło.
5) wyswietlic plain text wraz z zaznaczonymi blokami, ktore zostaly wykryte jako plagiat - (nie bedzie to super ladny doc/docx, ale zwykly plain text, przed preprocessingiem, wiec latwo czytelny, a plagiaty beda zaznaczone np innym tlem. powinno krokowej wystarczyc).

**Comment by b4rt3k** [comment]
Myśle że to trzeba zrobić tak:
- biorę 5 wyrazów z 1 pracy i porównuję z pierwszymi pięcioma z drugiej pracy (wyrazy od 1 do 5)
- przesuwam się w drugiej pracy o 1 wyraz w prawo i porównuję z pięcioma wyrazami (wyrazy od 2 do 6), itd. (ale chyba są jakieś bardziej efektywne algorytmy poszukiwania wzorca)
- jeśli już przejdę cały drugi tekst w poszukiwaniu wzorca z 1 pracy to trzeba przesunąć wzorzec z pracy 1
   
  Pytanie tylko o ile przesuwac wzorzec z 1 pracy. O 5 wyrazów czy o 1? 
  Dnia 22 marca 2013 13:32 Pasmek &lt;notifications@github.com&gt; napisał(a):
  Zastanawiam się jeszcze nad takim czymś. Jak podzielibyśmy ten tekst na bloki 5 wyrazowe to widzę taki problem. Co jeśli będziemy mieli taką sytuację:
  Tekst początkowy w pierwszej pracy:
  "Jednym z najprostszych praktycznych zastosowań algorytmu Rabina-Karpa jest wykrywanie plagiatu.."
  Tekst początkowy w drugiej pracy:
  "Wybór algorytmu. Jednym z najprostszych praktycznych zastosowań algorytmu Rabina-Karpa jest wykrywanie plagiatu.."
  I teraz dzielimy tekst na bloki 5 wyrazowe. Wzorzec zostanie wzięty z pierwszej pracy: "Jednym najprostszych praktycznych zastosowań algorytmu". Porównują go z 5 wyrazowym blokiem z drugiej pracy nie otrzymamy, że zdanie: "Jednym z najprostszych praktycznych zastosowań algorytmu Rabina-Karpa jest wykrywanie plagiatu." jest takie same.
  Mam nadzieję, że przedstawiłem to dobrze. Teraz właśnie patrząc na to co napisałem wyżej, to co jakby 5 razy przeszukać pracę przesuwając o jeden wyraz wzorzec zhaszowany?

**Comment by psmektalski** [comment]
Do końca nie rozumiem pytania. Myślę, że chodzi o to co teraz przedstawię.

1.) Tekst który będziemy przeszukiwać podzielimy na 5 tablic zawierające 5-wyrazowe bloki jako elementy.

Pierwsza tablica będzie się składała: 1 blok (wyrazy od 1:5), 2 blok(wyrazy od 6:10) itd
Druga tablica będzie się składała: 1 blok (wyrazy od 2:6), 2 blok (wyrazy od 7:11) tid
...
Piąta tablica będzie się składała: 1 blok (wyrazy od 5:10), 2 blok (wyrazy od 11:15) tid

2.) Wzorzec będzie pobierany z drugiego tekstu, ale tutaj zostanie tylko dzielony co 5 wyrazów.

Tablica wzorców : 1 blok (wyrazy od 1:5), 2 blok (wyrazy od 6:10)

3.) Teraz wzorzec będzie sprawdzany z każdą z tablic z punktu 1.).

4.) Następnie będzie trzeba policzyć procent powtórzenia tych tekstów, ale na tą chwilę nie wiem jak to zrobić.

Edit: Czekam na komentarze i wszelkie uwagi. Nawet bardzo krytyczne.

Edit2: Coś mi się przypomina, że jeszcze inaczej można postąpić w rozważanym przypadku. Teraz patrząc na efektywność to ona spadła. Spróbuje jeszcze poczytać o Rabinie-Karpie, bo w jego przypadku została zwiększona wydajność. Tylko nie pamiętam na tą chwilę jak i gdzie ja to czytałem.

**Comment by b4rt3k** [comment]
Do Pawła S
 
jak że ustalilismy że preprocessingowi poddejamy bloki a nie cały plik, to jak byś mógł przerobić swój algorytm tak aby przyjmował blok i zwracał blok po preprocessingu.
 
Pozdro bartek
Dnia 22 marca 2013 14:30 Pasmek &lt;notifications@github.com&gt; napisał(a):
Do końca nie rozumiem pytania. Myślę, że chodzi o to co teraz przedstawię.
Tekst który będziemy przeszukiwać podzielimy na 5 tablic zawierające 5-wyrazowe bloki jako elementy.Pierwsza tablica będzie się składała: 1 blok (wyrazy od 1:5), 2 blok(wyrazy od 6:10) itd
Druga tablica będzie się składała: 1 blok (wyrazy od 2:6), 2 blok (wyrazy od 7:11) tid
...
Piąta tablica będzie się składała: 1 blok (wyrazy od 5:10), 2 blok (wyrazy od 11:15) tid
Wzorzec będzie pobierany z drugiego tekstu, ale tutaj zostanie tylko dzielony co 5 wyrazów.Tablica wzorców : 1 blok (wyrazy od 1:5), 2 blok (wyrazy od 6:10)
Następnie będzie trzeba policzyć procent powtórzenia tych tekstów, ale na tą chwilę nie wiem jak to zrobić.—

**Comment by b4rt3k** [comment]
Zaimplementowałem wstępnie 2 algorytmy:
- KMP
- ten blokowy o którym była mowa
   
  Ad. KMP
  Zarówno ten algorytm jak i algorytm rabina Karpa działają na zasadzie że mają wzorzec i tekst w którym go poszukuja, czyli szukają stringa w większym stringu.
  Pierwszy z plików służy nam do pobierania wzorców a drugi do szukania tych wzorców w nim. Ten drugi więc wczytuje się do Stringa w całości i to jest nasz tekst. teraz odczytujemy z pierwszego pliku bloki po np. 5 wyrazów i szukamy ich wystapienia w tym dużym Stringu. jesli znajdziemy, to zapisujemy indeks wystapienia i wzorzec przesuwamy o 5 wyrazów, itd. Problem w tym że jesli te pliki sa już po preprocessingu, to te indeksy nie beda się zgadzać z indeksami przed preprocessingiem.
   
  Ad. bloki
  W tej wersji też mamy 2 pliki jeden z którego bierzemy wzorca, a drugi to ten w którym tych wzorcy szukamy. Bierzemy więc pierwsze 5 wyrazów z pliku z worcami i pierwsze 5 wyrazów z pliku drugiego. Oba bloki poddajemy preprocessingowi i porównujemy. jeśli się zgadzają, to zapisujemy indeks BLOKU. jesli nie to z pliku z danymi wyciagamy wyrazy 2-6, itd aż przejdziemy cały plik. Potem przewuwamy wzorzec na wyrazy 6-10 i robimy to samo. takie podejście pozwala na podstawie indeksów znaleźć dany blok w plain tekście przed preprocessingiem. Nie wczytujemy też żadnego z plików w całości do stringa. Nie jest to jednak ani algorytm rabina ani KMP ale jakiś nasz wymyślony (bo tamte algorytmy wymagają tekstu w całości). Trzeba by też zmienić wtedy preprocessing aby brał stringa przerabiał go i zwracał stringa.
   
  Oba działają, ale sa problemy takie jak napisałem. Co o tym myślicie?
  Dnia 22 marca 2013 14:30 Pasmek &lt;notifications@github.com&gt; napisał(a):
  Do końca nie rozumiem pytania. Myślę, że chodzi o to co teraz przedstawię.
  Tekst który będziemy przeszukiwać podzielimy na 5 tablic zawierające 5-wyrazowe bloki jako elementy.Pierwsza tablica będzie się składała: 1 blok (wyrazy od 1:5), 2 blok(wyrazy od 6:10) itd
  Druga tablica będzie się składała: 1 blok (wyrazy od 2:6), 2 blok (wyrazy od 7:11) tid
  ...
  Piąta tablica będzie się składała: 1 blok (wyrazy od 5:10), 2 blok (wyrazy od 11:15) tid
  Wzorzec będzie pobierany z drugiego tekstu, ale tutaj zostanie tylko dzielony co 5 wyrazów.Tablica wzorców : 1 blok (wyrazy od 1:5), 2 blok (wyrazy od 6:10)
  Następnie będzie trzeba policzyć procent powtórzenia tych tekstów, ale na tą chwilę nie wiem jak to zrobić.—

**Comment by b4rt3k** [comment]
Nie wrzuciłem  tego jeszcze bo tak jak pisałem sa problemy.
Dnia 25 marca 2013 12:25 b4rt3k408 &lt;b4rt3k408@o2.pl&gt; napisał(a):
Zaimplementowałem wstępnie 2 algorytmy:
- KMP
- ten blokowy o którym była mowa
   
  Ad. KMP
  Zarówno ten algorytm jak i algorytm rabina Karpa działają na zasadzie że mają wzorzec i tekst w którym go poszukuja, czyli szukają stringa w większym stringu.
  Pierwszy z plików służy nam do pobierania wzorców a drugi do szukania tych wzorców w nim. Ten drugi więc wczytuje się do Stringa w całości i to jest nasz tekst. teraz odczytujemy z pierwszego pliku bloki po np. 5 wyrazów i szukamy ich wystapienia w tym dużym Stringu. jesli znajdziemy, to zapisujemy indeks wystapienia i wzorzec przesuwamy o 5 wyrazów, itd. Problem w tym że jesli te pliki sa już po preprocessingu, to te indeksy nie beda się zgadzać z indeksami przed preprocessingiem.
   
  Ad. bloki
  W tej wersji też mamy 2 pliki jeden z którego bierzemy wzorca, a drugi to ten w którym tych wzorcy szukamy. Bierzemy więc pierwsze 5 wyrazów z pliku z worcami i pierwsze 5 wyrazów z pliku drugiego. Oba bloki poddajemy preprocessingowi i porównujemy. jeśli się zgadzają, to zapisujemy indeks BLOKU. jesli nie to z pliku z danymi wyciagamy wyrazy 2-6, itd aż przejdziemy cały plik. Potem przewuwamy wzorzec na wyrazy 6-10 i robimy to samo. takie podejście pozwala na podstawie indeksów znaleźć dany blok w plain tekście przed preprocessingiem. Nie wczytujemy też żadnego z plików w całości do stringa. Nie jest to jednak ani algorytm rabina ani KMP ale jakiś nasz wymyślony (bo tamte algorytmy wymagają tekstu w całości). Trzeba by też zmienić wtedy preprocessing aby brał stringa przerabiał go i zwracał stringa.
   
  Oba działają, ale sa problemy takie jak napisałem. Co o tym myślicie?
  Dnia 22 marca 2013 14:30 Pasmek &lt;notifications@github.com&gt; napisał(a):
  Do końca nie rozumiem pytania. Myślę, że chodzi o to co teraz przedstawię.
  Tekst który będziemy przeszukiwać podzielimy na 5 tablic zawierające 5-wyrazowe bloki jako elementy.Pierwsza tablica będzie się składała: 1 blok (wyrazy od 1:5), 2 blok(wyrazy od 6:10) itd
  Druga tablica będzie się składała: 1 blok (wyrazy od 2:6), 2 blok (wyrazy od 7:11) tid
  ...
  Piąta tablica będzie się składała: 1 blok (wyrazy od 5:10), 2 blok (wyrazy od 11:15) tid
  Wzorzec będzie pobierany z drugiego tekstu, ale tutaj zostanie tylko dzielony co 5 wyrazów.Tablica wzorców : 1 blok (wyrazy od 1:5), 2 blok (wyrazy od 6:10)
  Następnie będzie trzeba policzyć procent powtórzenia tych tekstów, ale na tą chwilę nie wiem jak to zrobić.—

**Comment by psmektalski** [comment]
Z algorytmem z blokami to tylko problem leży w tym, że nie jest to algorytm rabina-karpa? Bo jak dzięki temu osiągamy rezultat prawidłowy to myślę, żę zostawiamy to. Jak są jakieś inne problemy to się zastanowimy co z tym robić. 

Jak chodzi o jeszcze tego Rabina-karpa to jeszcze coś znalazłem. Chociaż jak zostawiamy tamto powyższe nie wiem czy się przyda. W podanych wcześniej naszych materiałach jest taki pseudokod używający filtru blooma:

function RabinKarpSet(string s[1..n], set of string subs, m) {
     set hsubs := emptySet
     for each sub in subs
           insert hash(sub[1..m]) into hsubs
     hs := hash(s[1..m])
     for i from 1 to n
           if hs ∈ hsubs
                if s[i..i+m-1] = a substring with hash hs
                     return i
           hs := hash(s[i+1..i+m])
      return not found
}

Ja widzę, że bardzo w podobny sposób jak nasz algorytm bloki tutaj zostały zrobione. Identycznie się przesuwamy w naszym algorytmie. Do końca nie rozumiem co tutaj się dzieje z tablicą hsubs.

Jak Bartku widzisz problem z tymi blokami to może zostać KMP. Może w tym przypadku przenosić w tych blokach informacje o stronie i na końcu jeszcze raz przeszukać, ale tylko stronę.

PS W edycji mam sformatowany poprawnie ten pseudokod, ale po commicie już nie. Nie wiem czemu.

**Comment by b4rt3k** [comment]
To na blokach działa. Sprawdze jeszcze jak z wydajnością i przepuszcze to przez jakis duzy tekst, ale chyba zostanie.
Dnia 25 marca 2013 16:15 Pasmek &lt;notifications@github.com&gt; napisał(a):
Z algorytmem z blokami to tylko problem leży w tym, że nie jest to algorytm rabina-karpa? Bo jak dzięki temu osiągamy rezultat prawidłowy to zostawiamy to. Jak są jakieś inne problemy to się zastanowimy co z tym robić.
Jak chodzi o jeszcze tego Rabina-karpa to jeszcze coś znalazłem. Chociaż jak zostawiamy tamto powyższe nie wiem czy się przyda. W podanych wcześniej naszych materiałach jest taki pseudokod używający filtru blooma:
function RabinKarpSet(string s[1..n], set of string subs, m) {
set hsubs := emptySet
for each sub in subs
insert hash(sub[1..m]) into hsubs
hs := hash(s[1..m])
for i from 1 to n
if hs ∈ hsubs
if s[i..i+m-1] = a substring with hash hs
return i
hs := hash(s[i+1..i+m])
return not found
}
Ja to rozumiem bardzo w podobny sposób jak nasz algorytm bloki został robiony. Identycznie się przesuwamy blokami jak tutaj.
Jak Bartku widzisz problem z tymi blokami to może zostać KMP. Może tutaj tylko przenosić w tych blokach informacje o stronie i na końcu jeszcze raz przeszukać, ale tylko stronę.

**Comment by psmektalski** [comment]
Wydaję mi się, że będzie łatwiej określać w tym sposobie procentowość pojawienia się plagiatu. Jak tylko czas będzie znośny sprawdzania tekstów, to również mi się wydaję, że najlepiej będzie jak ten algorytm zostanie.

**Comment by b4rt3k** [comment]
Wrzuciłem to porównywanie bloków. jak by się okazało że rabin karp byłby lepszy (bo tam hasze przyspieszają) to trzeba go będzie zaimplementowac bez zmian (bez bloków) albo się zastanowić jak go przerobić na bloki (aby był zysk z tych haszów tzn efektywne obliczenie hasza następbego bloku na podstawie bloku poprzedniego).
Dnia 25 marca 2013 16:48 Pasmek &lt;notifications@github.com&gt; napisał(a):
Wydaję mi się, że będzie łatwiej określać w tym sposobie procentowość pojawienia się plagiatu. Jak tylko czas będzie znośny sprawdzania tekstów, to również mi się wydaję, że najlepiej będzie jak ten algorytm zostanie.
